<?php

namespace App\Services;

use App\Models\User;
use App\Utils\URL;

/**
 * Builds native-client subscriptions without exposing an external controller.
 */
class ClientConfig
{
    /**
     * @param User $user
     * @param string $platform
     * @return string
     */
    public static function mihomo(User $user, $platform)
    {
        return self::renderMihomo(self::proxies($user), $platform);
    }

    /**
     * @param array $proxies
     * @param string $platform
     * @return string
     */
    public static function renderMihomo($proxies, $platform)
    {
        $proxyNames = array_map(static function ($proxy) {
            return $proxy['name'];
        }, $proxies);

        $lines = array(
            '# Generated by SSPanel Client API v1',
            '# Platform: ' . $platform,
            'mode: rule',
            'log-level: info',
            'ipv6: true',
            'allow-lan: false',
            'unified-delay: true',
            'tcp-concurrent: true',
        );

        if (in_array($platform, array('macos', 'windows', 'linux'), true)) {
            $lines[] = 'mixed-port: 7890';
        }

        $lines[] = 'proxies:';
        foreach ($proxies as $proxy) {
            $lines[] = '  - ' . self::json($proxy);
        }

        $autoGroup = array(
            'name' => 'Auto',
            'type' => 'url-test',
            'url' => 'https://www.gstatic.com/generate_204',
            'interval' => 300,
            'tolerance' => 100,
            'proxies' => $proxyNames,
        );
        $selectGroup = array(
            'name' => 'Proxy',
            'type' => 'select',
            'proxies' => array_merge(array('Auto', 'DIRECT'), $proxyNames),
        );

        $lines[] = 'proxy-groups:';
        $lines[] = '  - ' . self::json($autoGroup);
        $lines[] = '  - ' . self::json($selectGroup);
        $lines[] = 'rules:';
        $lines[] = '  - MATCH,Proxy';

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param User $user
     * @return string
     */
    public static function links(User $user)
    {
        $links = array();

        $items = array_merge(URL::getAllItems($user, 0, 1), URL::getAllItems($user, 1, 1));
        foreach ($items as $item) {
            $links[] = URL::getItemUrl($item, 1);
        }

        $vmess = trim(URL::getAllVMessUrl($user));
        if ($vmess !== '') {
            $links = array_merge($links, preg_split('/\r?\n/', $vmess));
        }

        foreach (SS2022::nodesForUser($user) as $node) {
            $links[] = SS2022::sip002Link($user, $node);
        }
        return implode("\n", $links) . (count($links) > 0 ? "\n" : '');
    }

    /**
     * @param User $user
     * @return array
     */
    public static function proxies(User $user)
    {
        $proxies = array();

        $items = array_merge(URL::getAllItems($user, 0, 1), URL::getAllItems($user, 1, 1));
        foreach ($items as $item) {
            $proxy = array(
                'name' => (string)$item['remark'],
                'type' => 'ss',
                'server' => $item['address'],
                'port' => (int)$item['port'],
                'cipher' => $item['method'],
                'password' => $item['passwd'],
                'udp' => true,
            );
            self::addPluginOptions($proxy, $item, $user);
            $proxies[] = $proxy;
        }

        foreach (URL::getAllVMessUrl($user, 1) as $item) {
            if (in_array($item['net'], array('kcp', 'http', 'quic'), true)) {
                continue;
            }
            $proxy = array(
                'name' => (string)$item['ps'],
                'type' => 'vmess',
                'server' => $item['add'],
                'port' => (int)$item['port'],
                'uuid' => $item['id'],
                'alterId' => (int)$item['aid'],
                'cipher' => 'auto',
                'udp' => true,
            );
            if ($item['net'] === 'ws') {
                $proxy['network'] = 'ws';
                $proxy['ws-opts'] = array('path' => $item['path']);
                if ($item['host'] !== '') {
                    $proxy['ws-opts']['headers'] = array('Host' => $item['host']);
                }
            }
            if ($item['tls'] === 'tls' || $item['net'] === 'tls') {
                $proxy['tls'] = true;
                if ($item['host'] !== '') {
                    $proxy['servername'] = $item['host'];
                }
            }
            $proxies[] = $proxy;
        }

        foreach (SS2022::nodesForUser($user) as $node) {
            $proxies[] = SS2022::mihomoProxy($user, $node);
        }

        return self::uniqueNames($proxies);
    }

    /**
     * @param array $proxy
     * @param array $item
     * @param User $user
     */
    private static function addPluginOptions(&$proxy, $item, User $user)
    {
        if ($item['obfs'] === 'plain') {
            return;
        }

        if ($item['obfs'] === 'simple_obfs_http' || $item['obfs'] === 'simple_obfs_tls') {
            $proxy['plugin'] = 'obfs';
            $proxy['plugin-opts'] = array(
                'mode' => $item['obfs'] === 'simple_obfs_http' ? 'http' : 'tls',
                'host' => $item['obfs_param'] !== '' ? $item['obfs_param'] : ($user->obfs_param ?: 'wns.windows.com'),
            );
            return;
        }

        if ($item['obfs'] === 'v2ray') {
            $proxy['plugin'] = 'v2ray-plugin';
            $proxy['plugin-opts'] = array(
                'mode' => 'websocket',
                'host' => $user->getMuMd5(),
                'path' => $item['path'],
            );
            if (strpos($item['obfs_param'], 'security=tls') !== false) {
                $proxy['plugin-opts']['tls'] = true;
            }
        }
    }

    /**
     * @param array $proxies
     * @return array
     */
    private static function uniqueNames($proxies)
    {
        $used = array(
            'Auto' => true,
            'Proxy' => true,
            'DIRECT' => true,
            'REJECT' => true,
        );
        foreach ($proxies as &$proxy) {
            $base = trim((string)$proxy['name']);
            $base = $base === '' ? 'Node' : $base;
            $name = $base;
            $suffix = 2;
            while (isset($used[$name])) {
                $name = $base . ' (' . $suffix . ')';
                $suffix++;
            }
            $proxy['name'] = $name;
            $used[$name] = true;
        }
        unset($proxy);
        return $proxies;
    }

    /**
     * JSON is valid YAML 1.2 and safely quotes credentials and node names.
     *
     * @param mixed $value
     * @return string
     */
    private static function json($value)
    {
        return json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }
}
